// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 29 Oct 2015 13:11:57 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.18929.0")]
[assembly: AssemblyFileVersion("1.0.18929.1311")]
